name: ebono_pos
description: "Ebono POS."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dropdown_search: ^6.0.1
  flutter_svg: ^2.0.10+1
  printing: ^5.13.3
  libserialport: ^0.3.0+1
  digital_scale: ^1.0.1+6
  pdf: ^3.11.1
  intl: ^0.19.0
  flutter_styled_toast: ^2.2.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  uuid: ^4.4.2
  connectivity_plus: ^3.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  #http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/
    - assets/data/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
